# Uncomment the next line to define a global platform for your project
 platform :ios, '9.0'

target 'Engaginbiz' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
	pod ‘GoogleSignIn’
	pod 'Firebase/Auth'
  	pod 'Firebase/Database'
	pod 'Firebase/Core'
	pod 'FBSDKCoreKit'
  	pod 'FBSDKLoginKit'
	pod 'TwitterKit'
	pod 'FBSDKCoreKit'
  	pod 'FBSDKLoginKit'
	pod 'TwitterKit'
	pod ‘GoogleSignIn’
	pod 'Bolts'
	pod 'Google/SignIn'
	pod 'UIColor+FlatColors'
 	pod 'Cartography'
  	pod 'ZLSwipeableViewSwift'
end
